### PR TITLE
Update to MXnet v1.2.0

### PR DESCRIPTION
**Pull request by cconvey**
Merges in the content of the MXnet `v1.2.0` _development_ branch, up through that branch's commit `f220ad07bb0cf572e66392f52acf6215ef0d1190` (dated April 14).

Note that MXnet has not yet created their `1.2.0` label, so once 1.2.0 is released we may have some more merging to do.

Here's the testing I've done for this PR:
- on skx12:
  - `make cpplint` passes.
  - `GTEST_FILTER=-*_PERF.*:-*Timing* make runtest` passes.
  - `train_cifar10.py` shows typical convergence rates.

- on titanxp50:
  - `GTEST_FILTER=-*_PERF.*:-*Timing* make runtest` passes.
  - `train_cifar10.py` shows typical convergence rates.
  - `pytest test_operator_gpu.py` segfaults because nGraph throws an exception with this text: `"ConvolutionBias is only supported with MKLDNN kernel."`.

### CODE REVIEW

**Comment by ashokei** [comment]
i am seeing some warnings while compiling , do you see similar : 

`src/ngraph/ngraph_utils.h:39:12: warning: ‘ngraph_bridge::ngraph_log_verbose’ defined but not used [-Wunused-variable]
 const bool ngraph_log_verbose = dmlc::GetEnv("MXNET_NGRAPH_VERBOSE", false);
`
`/root/ngraph_dist/include/ngraph/op/product.hpp:33:9: warning: multi-line comment [-Wcomment]
         ///                1 & 2 \\                                                         `

**Comment by cconvey** [comment]
@mbrookhart : I'm not working today, but here's the results of a run you asked for:
```
(python2b) cconvey@nervana-skx12:~/repos/NervanaSystems/ngraph-mxnet/to1.2$ time pytest tests/python/unittest 2>&1 | tee errors.txt
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-3.5.0, py-1.5.3, pluggy-0.6.0
rootdir: /localdisk/cconvey/repos/NervanaSystems/ngraph-mxnet/to1.2, inifile:
collected 496 items

tests/python/unittest/test_attr.py ....                                  [  0%]
tests/python/unittest/test_autograd.py ...............                   [  3%]
tests/python/unittest/test_contrib_autograd.py .........                 [  5%]
tests/python/unittest/test_contrib_io.py .                               [  5%]
tests/python/unittest/test_contrib_krprod.py ...                         [  6%]
tests/python/unittest/test_contrib_operator.py ...                       [  7%]
tests/python/unittest/test_contrib_text.py ..........                    [  9%]
tests/python/unittest/test_engine.py .                                   [  9%]
tests/python/unittest/test_exc_handling.py ......                        [ 10%]
tests/python/unittest/test_executor.py ...                               [ 11%]
tests/python/unittest/test_gluon.py ...............................F.... [ 18%]
.....                                                                    [ 19%]
tests/python/unittest/test_gluon_contrib.py ...........                  [ 21%]
tests/python/unittest/test_gluon_data.py ......s                         [ 22%]
tests/python/unittest/test_gluon_data_vision.py .....                    [ 23%]
tests/python/unittest/test_gluon_model_zoo.py .                          [ 24%]
tests/python/unittest/test_gluon_rnn.py ...............                  [ 27%]
tests/python/unittest/test_image.py ..FF......                           [ 29%]
tests/python/unittest/test_infer_shape.py .........                      [ 31%]
tests/python/unittest/test_init.py ....                                  [ 31%]
tests/python/unittest/test_io.py .......s                                [ 33%]
tests/python/unittest/test_kvstore.py .........                          [ 35%]
tests/python/unittest/test_loss.py ........ss......                      [ 38%]
tests/python/unittest/test_metric.py ........                            [ 40%]
tests/python/unittest/test_metric_perf.py .                              [ 40%]
tests/python/unittest/test_model_parallel.py .                           [ 40%]
tests/python/unittest/test_module.py ..........F....                     [ 43%]
tests/python/unittest/test_multi_device_exec.py ..                       [ 43%]
tests/python/unittest/test_ndarray.py .................................. [ 50%]
........s                                                                [ 52%]
tests/python/unittest/test_operator.py ...........................s.s^[^[... [ 59%]
......................................................................F  [ 73%]
tests/python/unittest/test_optimizer.py ...s......s...                   [ 76%]
tests/python/unittest/test_profiler.py .........                         [ 78%]
tests/python/unittest/test_random.py ................                    [ 81%]
tests/python/unittest/test_recordio.py ...                               [ 82%]
tests/python/unittest/test_rnn.py ..............                         [ 84%]
tests/python/unittest/test_sparse_ndarray.py ........................... [ 90%]
.........                                                                [ 92%]
tests/python/unittest/test_sparse_operator.py ....
real    880m16.978s
user    1870m32.524s
sys     1038m19.312s
```

I checked in on the script a few times, and I got the impression that it ran pretty quickly until the `test_profiler.py` step.  Not sure if any of the steps after that one were fast or slow.

**Comment by cconvey** [comment]
@ashokei @mbrookhart : I'm only noticing multi-line-comment warnings in nGraph's header files.  Would it make sense to treat them as out-of-scope for this PR?

The only obvious alternative is to suppress that warning (perhaps selectively) when building MXnet, but I'm not sure that's a good idea long-term.

**Comment by mbrookhart** [comment]
Yeah, we can move that to another PR. Thanks for the test results, looks like the only issues you're hitting we already know about.

**Comment by cconvey** [comment]
@ashokei Given the discussion above, are you okay with the merge once I make my man Jenkins happy?

**Comment by cconvey** [comment]
TESTNOW

**Comment by cconvey** [comment]
TESTNOW

**Comment by lnguyen-nvn** [comment]
Please do not merge till we sort out all failed test cases.

**Pull request merged**
