### PR TITLE
remove BN skipping because MKLDNN improved their generic kernel

### PR DESCRIPTION
**Pull request by mbrookhart**

### CODE REVIEW

**Comment by mbrookhart** [comment]
TESTNOW

**Comment by lnguyen-nvn** [comment]
TESTNOW

**Comment by lnguyen-nvn** [comment]
TESTNOW

**Comment by lnguyen-nvn** [comment]
TESTNOW

**Comment by mbrookhart** [comment]
Will be fixed by https://github.com/NervanaSystems/ngraph/pull/1343

**Comment by mbrookhart** [comment]
TESTNOW

**Comment by mbrookhart** [comment]
TESTNOW

**Comment by mbrookhart** [comment]
TESTNOW

**Comment by mbrookhart** [comment]
TESTNOW

**Pull request merged**
